# Generated by Django 3.2.13 on 2025-02-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInfo_forTest',
            fields=[
                ('sample_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='样本ID')),
                ('series', models.CharField(max_length=10, verbose_name='实验系列')),
                ('group', models.CharField(max_length=50, verbose_name='分组')),
                ('cell_tissue_type', models.CharField(max_length=50, verbose_name='细胞/组织类型')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='详细信息')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('medical_condition', models.CharField(default='Normal', max_length=20, verbose_name='医学状态')),
                ('experimental_method', models.CharField(max_length=50, verbose_name='实验方法')),
            ],
            options={
                'verbose_name': '生物样本',
                'db_table': 'SampleInfo',
                'ordering': ['-sample_id'],
            },
        ),
    ]
